# Generated by Django 2.1.1 on 2018-09-13 08:45

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='invoice name')),
                ('description', models.TextField(blank=True, max_length=200, verbose_name='payment description')),
                ('date_added', models.DateField(default=datetime.datetime.now, verbose_name='date added')),
                ('date_deadline', models.DateField(verbose_name='date due')),
                ('amount_cents', models.BigIntegerField(verbose_name='amount in cents')),
                ('groups', models.ManyToManyField(to='auth.Group')),
            ],
            options={
                'verbose_name': 'invoice',
                'verbose_name_plural': 'invoices',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_cents', models.BigIntegerField(default=0, verbose_name='amount in cents')),
                ('date_paid', models.DateField(default=datetime.datetime.now, verbose_name='date paid')),
                ('var_symbol', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(9999999999)])),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.Invoice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'payment',
                'verbose_name_plural': 'payments',
            },
        ),
    ]
