# Generated by Django 2.1.1 on 2018-09-04 07:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(verbose_name='date added')),
                ('date_deadine', models.DateTimeField(verbose_name='date due')),
                ('payment_group', models.TextField(max_length=64, verbose_name='payment group')),
                ('description', models.TextField(max_length=200, verbose_name='payment description')),
                ('amount_cents', models.BigIntegerField(verbose_name='amount in cents')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.BigIntegerField(verbose_name='amount in cents')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.Invoice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
