# Generated by Django 2.1.1 on 2018-09-13 09:09

from django.conf import settings
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='var_symbol',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(9999999999)], verbose_name='associated var symbol'),
        ),
        migrations.AlterUniqueTogether(
            name='payment',
            unique_together={('invoice', 'user')},
        ),
    ]
