# Generated by Django 2.1.1 on 2018-09-04 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='date_deadine',
            new_name='date_deadline',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='amount',
            new_name='amount_cents',
        ),
    ]
