# Generated by Django 2.1.2 on 2018-10-20 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_auto_20180913_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='date_paid',
            field=models.DateField(null=True, verbose_name='date paid'),
        ),
    ]
