# Generated by Django 2.1.1 on 2018-09-07 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_auto_20180906_1218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertogroup',
            name='group',
        ),
        migrations.RemoveField(
            model_name='usertogroup',
            name='user',
        ),
        migrations.AlterField(
            model_name='invoicetogroup',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group'),
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='UserToGroup',
        ),
    ]
