# Generated by Django 2.1.2 on 2018-10-24 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_auto_20181024_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='account_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.AccountInfo'),
        ),
    ]
