# Generated by Django 2.1.1 on 2018-09-07 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('payments', '0004_auto_20180907_1145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoicetogroup',
            name='group',
        ),
        migrations.RemoveField(
            model_name='invoicetogroup',
            name='invoice',
        ),
        migrations.AddField(
            model_name='invoice',
            name='groups',
            field=models.ManyToManyField(to='auth.Group'),
        ),
        migrations.DeleteModel(
            name='InvoiceToGroup',
        ),
    ]
