# Generated by Django 2.1.1 on 2018-09-08 08:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_auto_20180908_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='date added'),
        ),
    ]
