# Generated by Django 2.1.2 on 2018-11-10 00:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_auto_20181110_0146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='groups',
            field=models.ManyToManyField(blank=True, to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payment',
            name='date_paid',
            field=models.DateField(blank=True, null=True, verbose_name='date paid'),
        ),
    ]
