# Generated by Django 2.1.1 on 2018-09-08 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_auto_20180908_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='description',
            field=models.TextField(blank=True, max_length=200, verbose_name='payment description'),
        ),
    ]
