# Generated by Django 2.1.1 on 2018-09-09 07:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_auto_20180909_0755'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='var_symbol',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(9999999999)]),
        ),
    ]
