# Generated by Django 2.1.1 on 2018-09-10 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_payment_var_symbol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount_cents',
            field=models.BigIntegerField(default=0, verbose_name='amount in cents'),
        ),
    ]
